services:
  web:
    image: nginx
    expose:
      - 80
    links:
      - php
    volumes:
      - ./templates:/etc/nginx/templates
      - ./:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./:/usr/share/nginx/html:ro

networks:
  internal:
     driver: bridge